### ISSUE TITLE
Sokoban level 3h: got stuck in walled tile outside map

### ISSUE THREAD

**Issue by Joel-A-Pereira** [UnNetHack/UnNetHack#17]
I fell through the final level of sokoban by walking over a pit and was teleported to walled tile just outside the level 3h map. And I guess there's no way to get out. [https://nethackwiki.com/wiki/Sokoban_Level_3h](see level 3h here) notice the empty tile to the right of the down stair, that's where I fell and got stuck. I've not yet quit the game just incase there's a way out...

**Comment by tr00per** [comment]
My noobish question: did you try digging? Or is it impossible on Sokoban levels?

**Comment by Joel-A-Pereira** [comment]
The wiki says it isn't in Vanilla, and I assumed so for this too. In any case, I'm practically stripped of all my equipment because just before falling, I tried to pass between boulders; so just have my Excalibur with me. Hehe.

**Comment by bhaak** [comment]
You're probably out of luck if you have no inventory and no intrinsic teleportation.

This level is originally from GruntHack and given Grunt's sadistic trait, this could have been intentional. You never know.

Sorry for your lost game.
