### ISSUE TITLE
makemon trying to create a monster at <81,0>?

### ISSUE THREAD

**Issue by Singhend** [UnNetHack/UnNetHack#40]
Recent run on an HF server using UnNetHack 6.0.3
On a couple of levels - primarily VotD and the elemental planes - I was getting the following errors - 

        makemon trying to create a monster at <81,0>?
        Program in disorder; you probably should S)ave and restart the process.
        makemon trying to create a monster at <81,0>?
        Program in disorder; you probably should S)ave and restart the process.
        makemon trying to create a monster at <81,0>?
        Program in disorder; you probably should S)ave and restart the process.

Restarting had no effect but going to the next level stopped until for a while. Not sure whether this is an HF server issue or an UnNetHack issue.

**Comment by k21971** [comment]
That is definitely an UnNetHack issue, not the server.

**Comment by bhaak** [comment]
We already got some reports about that. I can't reproduce it locally. The fuzzer didn't show it but then the fuzzer won't reach the VotD easily.

**Comment by bhaak** [comment]
The problem why I couldn't reproduce it was that it only happened after the wizard of yendor had been killed.

This now revealed two bugs. One in the level flipping code 795e1a11eba5e6a121a899c6f77018d8649b5de9 and the other in not putting monsters around branch stairs when on the ascension run 21f1f5719bd93b538cec793dda170326d69946ea.
