### ISSUE TITLE
Request - add #name of item on floor (as in vanilla)

### ISSUE THREAD

**Issue by Singhend** [UnNetHack/UnNetHack#41]
It would be nice to be able to #name an item on the floor (as you can in vanilla).
Two specific use cases
 You've kicked that gray stone, it hurt, you want to name it 'loadstone' without picking it up 
 That scroll on the shop floor causes your pet to flee - let's name it scare monster without risking paying for used goods

I guess the alternate in both causes is to automatically name them as with other unique messages.

**Comment by bhaak** [comment]
Naming items on the floor has been added with 7de11f7f468920.

Automatically naming stuff when things happen is likely problematic if the player doesn't start the action (like as when engraving).
