### ISSUE TITLE
6.0.3 - when max power is zeroed by anti-magic fields, my power no longer goes up when i gain a level

### ISSUE THREAD

**Issue by danpritts** [UnNetHack/UnNetHack#43]
Hi,
6.0.3 on MacOS latest, locally compiled with no configure options except --dir's

My tourist ran into some anti-magic fields early on and *max* power went down to zero.  Based on spoilers on nethackwiki, losing max power does seem to be intended, so no problem there.

However, since that happened, I no longer get a bump in max power when I gain a level.

I've come across a few potions of gain energy so my level 22 character now has max power of 31.  

This is an interesting challenge, so I'm not sure whether it is intentional or a bug, but I thought I'd report it.

**Comment by bhaak** [comment]
It's intentional. Tourists don't gain any magic power when leveling up.

But this issue reminded me that I wanted to change it slightly so tourists get at least a chance to cast their own special spell.

They get 1 PW max per level up now with commit 960661c772.
