### ISSUE TITLE
Stair travel (via <>) does not work when known stairs are covered by objects.

### ISSUE THREAD

**Issue by elunna** [UnNetHack/UnNetHack#55]

**Comment by bhaak** [comment]
Seems to have always been this way. So not a regression.

I'd categorize it as a minor UI inconvenience as using travel will find known stairs under objects. It's still a bug though.

**Comment by elunna** [comment]
I think I have a solution here: https://github.com/elunna/hackem/commit/ebb6eed72c6b9eee1fb92adb4b269a328935277e

I copied over the checks from regular getpos(). Tested on levels  with 1 set of stairs, and levels with a branch (>) stairs, and also with a mimic mimicing (<). Seems to work with all those cases.
